### ISSUE TITLE
Use of a UI library/framework

### ISSUE THREAD

**Issue by livtanong** [snpeek/snpeek.github.io#13]
I've noticed that the app uses bare javascript to manipulate the DOM to create and update the UI.
While this is fine while the app is in its simplest stage, the project may benefit from a UI framework/platform to abstract away DOM concerns, and allow contributors to make faster progress with the UI. Is this something you guys are open to?

I'm familiar with React, Vue, and Svelte, with my preference being Svelte.

All of them are compatible with TypeScript, and so much of the internal logic of SNPeek should still work.

Adopting any of these will add a bit of overhead in terms of build process, with the worst offender being React (you choose any number of build runners and packagers, and configure them a million ways to come up with a working output) and the cleanest being Svelte. (it comes with its own build toolchain, making things easier to deal with)

Meanwhile, React is the most popular (and therefore easiest to get contributors onboard)

Regardless of the choice and the tradeoffs, going with *any* of them is going to provide a productivity boost over the status quo.

**Comment by d6e** [comment]
Yeah, I'm not familiar with any frontend frameworks and this is the first full client side webapp I've ever made. I wrote it in vanilla js because it was a weekend project and I didn't have the time to dedicate to learning a framework. Also it's less overhead so the performance should be better. But I understand that might be difficult if the codebase gets bigger. I'd be open to it, my main concern is performance, specifically with features like streaming in vcf files. If that's still possible to do within a framework (I suspect it would be?), I'd be open to that. I don't have the spare cycles right between work to spend on that so if you want to take it on feel free, you have my blessing.

**Comment by livtanong** [comment]
In general frontend frameworks shouldn't have trouble with streaming things and handling large files--in a manner of speaking, the framework wouldn't be "doing work" during that time. 

Most dropped frames happen when:
- large calculations happen amid UI updates (can be mitigated with a loading screen)
- a large number of elements are being displayed such as in very large lists or grids (can be mitigated with using lazy lists--this is the standard in mobile apps, and pretty much all UI frameworks have this in some way or another, as it is a very common requirement)
- improperly structured code (can be mitigated by... structuring code properly :P)

In general, for an app like this, performance isn't really much of an issue, especially since it's not a game, or a mission-critical process, or an app that one would use every day (where a bad experience compounds over time).

Regardless, I'm confident that from what I understand about the scope of this app, we'll be fine.

And yes, I will happily take on this task after #17 .

**Comment by livtanong** [comment]
#20 has been merged
